### ISSUE TITLE
regarding adopting your code to different data set

### ISSUE THREAD

**Issue by wenouyang** [DeepSegment/ConvNet-Segment#2]
Hi, thank you for sharing the code. I am having a data set which involves images with 5 input channels, and output class is 2, i.e., I am studying a binary semantic segmentation problem. which part of your code should be changed to adopt this kind of use scenario? Thanks.

**Comment by txzhao** [comment]
Hey, thanks for noticing our work. From what I've seen right now, following changes should at least be done given your situation:

-------- For "inception_FCN.py" --------
1. in line 21, change the path to your dataset, e.g. tf.flags.DEFINE_string("data_dir", "Data_zoo/your_dataset/", "path to dataset")
2. change NUM_OF_CLASSES = 22 to 2 in line 59 since you are dealing with a binary problem;
3. in line 139, change the shape of placeholder to [None, IMAGE_SIZE, IMAGE_SIZE, 5] for your input images.

-------- For "BatchDatsetReader.py" --------
1. in line 52, change range(3) to range(5) since your input has 5 channels;
2. in line 39, you need to change True to False because the "True" case deals with PASCAL dataset.

-------- For "read_MITSceneParsingData.py" --------
1. in line 11, change DATA_URL to the one of your dataset and also it's better if you rename the pickle file in line 15 as you like;
2. you probably need to change line 58 according to the directory of your dataset. Please see the printout of line 60 to check if the directory is correct.

-------- For "colorize.py" --------
This script serves for colorizing the greyscale output images. I think you could skip this script for now due to its low priority in your workflow. For simplification, just comment out line 224 in inception_FCN.py and see if everything else works fine first and then come back to this afterwards. 

After you change the above things, you should be able to transplant your dataset into our code. You may first try the "visualize" mode by changing line 24 in inception_FCN.py to see how it works. Perhaps there are something else that you need to change but I miss because I haven't touched the code for a long time. If still there are bugs in the code, please let us know and we'll try our best to help you. If you like our repo, we would appreciate your star! Cheers!
