### ISSUE TITLE
TypeError: Expected binary or unicode string, got None

### ISSUE THREAD

**Issue by lily10086** [DeepSegment/ConvNet-Segment#4]
when I train MITSceneParsingData ,It throws an exception,I use the  following code:
     inception_FCN.py:
          tf.flags.DEFINE_string('checkpoint_path', 'logs','The path to a checkpoint from which to fine-tune.')
          train_records,valid_records=dataset.create_image_lists(FLAGS.data_dir)
    read_MITSceneParsingData.py:
           def create_image_lists(image_dir):
                   ....
                       return image_list['training'],image_list['validation']
    and I download MITSceneParsingData and unzip it.

**Comment by lily10086** [comment]
Oh,sorry.I solve the problem,I didn't download the inception_v3.ckpt.

**Comment by engahmed1190** [comment]
hello @lily10086 

what do you mean by download inception_v3.ckpt. , i am facing the same issue now 

Setting up Saver...
```
Traceback (most recent call last):
  File "inception_FCN.py", line 275, in <module>
    tf.app.run()
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "inception_FCN.py", line 190, in main
    init_fn = _get_init_fn()
  File "inception_FCN.py", line 116, in _get_init_fn
    return slim.assign_from_checkpoint_fn(checkpoint_path, variables_to_restore, ignore_missing_vars=FLAGS.ignore_missing_vars)
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/contrib/framework/python/ops/variables.py", line 638, in assign_from_checkpoint_fn
    reader = pywrap_tensorflow.NewCheckpointReader(model_path)
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 110, in NewCheckpointReader
    return CheckpointReader(compat.as_bytes(filepattern), status)
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/util/compat.py", line 65, in as_bytes
    (bytes_or_text,))
TypeError: Expected binary or unicode string, got None
```

how i can resolve that

**Comment by txzhao** [comment]
hi @engahmed1190,

If I understand correctly, you are now in the training mode. To fine-tune the whole net, you should first download the checkpoint of inception v3 model manually and then run inception_FCN.py. For more details, you can find it in this part of the readme file (https://github.com/DeepSegment/FCN-GoogLeNet/blob/master/README.md#fine-tune-whole-net).

**Comment by engahmed1190** [comment]
Hello @txzhao 

i have added that , when i reviewed the fine-tune i found that 


> (1) Add upsampling layer on the top of inception v3; freeze lower layers and just train the output layer of the pretrained model and the upsampling layers:
> 
> To acheive this, change tf.flags.DEFINE_string('trainable_scopes', ...) to 'InceptionV3/Logits,InceptionV3/Upsampling'. Make sure you've set the flag of skip_layers to the architecture you want. Set mode to train and run inception_FCN.py. If the code is planned to run on PDC clusters, run sbatch ./batchpyjobunix.sh to submit your job to the queuing system Slurm.
> 
> (2) Fine-tune all the variables:
> 
> Change tf.flags.DEFINE_string('trainable_scopes', ...) to be None. Also remember to change tf.flags.DEFINE_string('checkpoint_path', ...) to 'logs'. Run inception_FCN.py again. If the code is planned to run on PDC clusters, run sbatch ./batchpyjobunix.sh to submit your job to the queuing system Slurm.


here you mentioned that model will be trained twice or i missed something , 

what is the reason for that i feel lost in this point 

i start the training using 
`tf.flags.DEFINE_string( 'trainable_scopes', None,'Comma-separated list of scopes to filter the set of variables to train.' 'By default, None would train all the variables.')`


what is the effect of None and 'InceptionV3/Logits,InceptionV3/Upsampling' 



Thanks, this code seems reasonable and great !

**Comment by txzhao** [comment]
Hi,

The reason for the two steps in fine-tuning lies in that it could provide a warm start for the checkpoint and accelerate the training process since this inception v3 model is pre-trained on a classification image set while it is now transferred to a semantic segmentation task. Actually it is a common practice to use this two-step fine-tuning in transfer learning. Here are some links that I found useful for a better explanation:
1. https://cs.stanford.edu/~quocle/tutorial2.pdf (search for 'fine-tune' in this tutorial)
2. https://datascience.stackexchange.com/questions/17719/right-way-to-fine-tune-train-a-fully-connected-layer-as-a-separate-step

As for the flag 'trainable_scopes', when it's set to 'None' (no restriction to trainable parameters), it means all the parameters in the network will be trained and updated during the training process. This actually corresponds to fine-tuning the whole net (the second step); When it is set to 'InceptionV3/Logits,InceptionV3/Upsampling', it means only parameters in the layers 'Logits' and 'Upsampling' are trained and updated while other parameters in the lower layers are frozen. This kind of corresponds to the first step.

I really hope I correctly understand your questions and my answer could help you in some way. Please don't hesitate to ask me if you have any further question. Cheers!
