### ISSUE TITLE
train MITScence Parsing

### ISSUE THREAD

**Issue by lily10086** [DeepSegment/ConvNet-Segment#8]
In your readme.md,It shows MIT Scene Parsing has goog result,But when I train it,The results is not good.
Can you share me the training parameters??

![inp_0](https://user-images.githubusercontent.com/33013509/33006410-3caa891e-ce05-11e7-8682-6cae5a8eb0be.png)

![gt_0](https://user-images.githubusercontent.com/33013509/33006418-45b85932-ce05-11e7-993b-7f864ac4f84e.png)
![pred_0](https://user-images.githubusercontent.com/33013509/33006430-4f29ebb6-ce05-11e7-8988-e1aeb5bf2414.png)

**Comment by txzhao** [comment]
Hi,
We documented our parameter settings in our [report](https://github.com/DeepSegment/FCN-GoogLeNet/blob/master/doc/report.pdf). For the learning rate, we set it to 0.0032, which is the same with the one mentioned in the original paper. But for the dataset MIT Scene Parsing, I remember that we changed it to 0.002 or 0.0016 (unfortunately we didn't put that in our report). Please try this and let me know if works. 
One thing I would like to say is that MIT Scene Parsing is a much challenging dataset compared to PASCAL VOC since it contains 150 classes and almost all the images contain multiple objects. So I would expect that the learning performance will not be as good as that of PASCAL VOC.

**Comment by lily10086** [comment]
Thanks,I will try it .
